shipping_methods:
  1: #'Colombia'
    attributes:
      name: 'Transporte propio'
      shipping_zone_id: 1

shipping_categories:
  1:
    attributes:
      name: Pesados
  2:
    attributes:
      name: Livianos

shipping_rates:
  1: #'FREE, shipping_rate_type => Order, shipping_category => Pesados'
    attributes:
      shipping_method_id: 1
      rate: 0.00
      shipping_rate_type_id: 2
      shipping_category_id: 1
      minimum_charge: 25.00
      position: 1
      active: true
  

prototypes:
  1: #Destornilladores
    attributes:
      name: Destornillador
      active: true
  2: #Alicates
    attributes:
      name: Alicates
      active: true

properties:
  1: #largo del destornillador
    attributes:
      identifing_name: destornillador-largo
      display_name: largo
  2: #ancho del destornillador
    attributes:
      identifing_name: destornillador-ancho
      display_name: ancho
  3: #tipo de destornillador
    attributes:
      identifing_name: destornillador-tipo
      display_name: tipo
  
prototype_properties:
  1: #'largo del destornillador'
    attributes:
      property_id: 1
      prototype_id: 1
  2: #'ancho del destornillador'
    attributes:
      property_id: 2
      prototype_id: 1
  3: #'tipo de destornillador'
    attributes:
      property_id: 3
      prototype_id: 1
  

product_types:
  1: #Accesorios
    attributes:
      name: Accesorios
      parent_id:
      active: true
  2: #Belem y Madeiras
    attributes:
      name: Belem y Madeiras
      parent_id: 1
      active: true
  3: #Cocina Acero Inoxidable
    attributes:
      name: Cocina Acero Inoxidable
      parent_id: 
      active: true
  4: #Linea de Lujo
    attributes:
      name: Linea de Lujo
      parent_id: 3
      active: true      
  5: #Teec
    attributes:
      name: Teec
      parent_id: 3
      active: true      
  6: #Herramientas
    attributes:
      name: Herramientas
      parent_id: 
      active: true      
  7: #Master
    attributes:
      name: Master
      parent_id: 6
      active: true      
  8: #Pro
    attributes:
      name: Pro
      parent_id: 6
      active: true      
  9: #Hogar
    attributes:
      name: Hogar
      parent_id: 
      active: true      
  10: #Cutelaria
    attributes:
      name: Cutelaria
      parent_id: 9
      active: true      
  11: #Farroupilha
    attributes:
      name: Farroupilha
      parent_id: 9
      active: true
  12: #Samovares
    attributes:
      name: Samovares
      parent_id: 9
      active: true      
  13: #Jardineria
    attributes:
      name: Jardineria
      parent_id: 
      active: true
  14: #Multi
    attributes:
      name: Multi
      parent_id: 13
      active: true
  15: #Muebles
    attributes:
      name: Muebles
      parent_id: 
      active: true
  16: #Delta
    attributes:
      name: Delta
      parent_id: 15
      active: true            
brands:
  1:
    attributes:
      name: Tramontina
suppliers:
  1:
    attributes:
      name: Tramontina Colombia
      email: test@test.com

tax_categories:
  1: #Iva 16 %
    attributes:
      name: iva-general

tax_rates:
  1: #General
    attributes:
      percentage: 16
      tax_category_id: 1
      state_id: 1
      start_date: '2012-01-01 14:30:29'
      active: true
  
products:
  1: #'Destornillador'
    attributes:
      name: Destornillador
      description: '<p>Destonillador linea master.</p>'
      product_keywords:
        - destornillador
      tax_category_id:
      brand_id: 1
      product_type_id: 7
      prototype_id: 1
      shipping_category_id: 1
      tax_category_id: 1
      active: true
      permalink: destornillador
      available_at: '2011-11-05 14:30:29'
      deleted_at:
      meta_keywords: destornillador
      meta_description: destornillador profesional
      featured: true
      description_markup: "Destornillador Linea Master"

product_properties:
  1: #'Destornillador, Largo'
    attributes:
      product_id: 1
      property_id: 1
      position: 1
      description: '6in, 8in, 10in'
  2: #'Destornillador, Ancho'
    attributes:
      product_id: 1
      property_id: 2
      position: 2
      description: '3/16, 1/4, 5/8'
  3: #'Destornillador, tipo'
    attributes:
      product_id: 1
      property_id: 3
      position: 3
      description: 'Plano, Cruz'
  
inventories:
  1:
    attributes:
      count_on_hand: 11
      count_pending_to_customer: 5
      count_pending_from_supplier: 0

variants:
  1: #'Destornillador 1'
    attributes:
      product_id: 1
      sku: 0000-0000-000001
      name:
      price: 3000
      cost: 1000
      brand_id: 1
      inventory_id: 1
  2: #'Destornillador 2'
    attributes:
      product_id: 1
      sku: 0000-0000-000002
      name:
      price: 3000
      cost: 1000
      brand_id: 1
      inventory_id: 2
  
variant_properties:
  1: #'Destornillador 1'
    attributes:
      variant_id: 1
      property_id: 1
      description: 6in
      primary: 1
  2: #'Destornillador 2'
    attributes:
      variant_id: 2
      property_id: 1
      description: 8in
      primary: 1

variant_suppliers:
  1:
    attributes:
      variant_id: 1
      supplier_id: 1
      cost: 10.00
      total_quantity_supplied: 0
      min_quantity: 11
      max_quantity: 1001
      active: true
  2:
    attributes:
      variant_id: 2
      supplier_id: 1
      cost: 10.00
      total_quantity_supplied: 0
      min_quantity: 12
      max_quantity: 1002
      active: true
